---
- name: "Install apache web server"
  hosts:  all
  become: true
  tasks:
    - name: "Install apache, php and firewalld"
      yum:
        name:
          - httpd
          - php
          - firewalld
        state:  present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: "check state service httpd, php, firewalld"
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - firewalld
      when: ansible_distribution == "RedHat"
    - name: "Permite apache port "
      firewalld:
        state:  enabled
        permanent: true
        port: 80/tcp
      when: ansible_distribution == "RedHat"

    #----------------Installation in ubuntu----------------------------#
    - name: "Install apache php and firewalld"
      apt:
        name:
          - apache2
          - php
          - firewalld
        state:  present
      when: ansible_distribution == "Ubuntu"
    - name: "check state service"
      service:
        name: "{{ item }}"
        state:  restarted
        enabled: yes
      with_items:
          - apache2
          - firewalld
  
    - name: "Permite apache port"
      firewalld:
        state:  enabled
        permanent: true
        port: 80/tcp
      when: ansible_distribution == "Ubuntu"
