- name: "Install mariadb Server RedHat"
  yum:
    name: mariadb-server
    state: present
  when: ansible_distribution == "RedHat"

- name: "Install mariadb Server on Ubuntu"
  apt:
    name: mariadb-server
    state: present
  when: ansible_distribution == "Ubuntu"
